# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 500, 81, 61))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ready.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.back2menu = QtWidgets.QPushButton(self.centralwidget)
        self.back2menu.setGeometry(QtCore.QRect(690, 20, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.back2menu.setFont(font)
        self.back2menu.setObjectName("back2menu")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 480, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.acceptBut = QtWidgets.QPushButton(self.centralwidget)
        self.acceptBut.setGeometry(QtCore.QRect(550, 20, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.acceptBut.setFont(font)
        self.acceptBut.setObjectName("acceptBut")
        self.LabelImage = QtWidgets.QLabel(self.centralwidget)
        self.LabelImage.setGeometry(QtCore.QRect(170, 110, 471, 351))
        self.LabelImage.setScaledContents(True)
        self.LabelImage.setObjectName("LabelImage")
        self.ans = QtWidgets.QSpinBox(self.centralwidget)
        self.ans.setGeometry(QtCore.QRect(200, 531, 291, 21))
        self.ans.setObjectName("ans")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите уровень сложности:"))
        self.back2menu.setText(_translate("MainWindow", "В меню"))
        self.label_2.setText(_translate("MainWindow", "Сколько всего треугольников на картинке?"))
        self.acceptBut.setText(_translate("MainWindow", "Начать игру"))
        self.LabelImage.setText(_translate("MainWindow", "TextLabel"))
